### ISSUE TITLE
Fix registration UX

### ISSUE THREAD

**Issue by john-light** [aragon/aracon-website#56]
Right now when a visitor clicks the "buy tickets" link it takes them to Ti.to which does not allow them to pay with crypto. Instead the visitor has to figure out that they need to go to the registration page first, which is a different link, to pay with crypto.

I propose that we remove the "register" link in the header menu and convert the "buy tickets" button into a "register" button that links to the registration page. This should make the registration process more intuitive for website visitors.

**Comment by Smokyish** [comment]
@john-light We put the Buy Tickets button with a direct link to Tito so it is as straightforward for a user as possible to just get a ticket. And then we left the Register page there just for that reason, if one then starts to wonder if they can pay with crypto, going to that page would give them all the information, how to apply for a community ticket, how to buy with crypto etc. This choice was supported by both me and @owisixseven at the time, but if we are getting feedback from users that it is definitely a bad choice, we can consider revisiting this.

So the decision was made to streamline the user experience as much as possible while retaining the additional information and options on the site, where as this change would negate some of those effects.

**Comment by john-light** [comment]
> if we are getting feedback from users that it is definitely a bad choice, we can consider revisiting this.

@Smokyish I'm giving you that feedback now. It's very confusing that there are two buttons to register, and one of them takes you to a place that doesn't even accept crypto.

Another reason is what if someone doesn't realize they can get a community ticket on the registration page and they click the buy ticket button and pay for the ticket, then only find out at or after the  conference that they could have gotten a community ticket? This is just a bad UX.

**Comment by john-light** [comment]
I would also change the "register here" button on the registration page to "pay with card" since paying with crypto will also register them i.e. it's not that one button will register them and the other won't, both payment methods will successfully register the user so the only difference between the buttons is the payment method.

**Comment by luisivan** [comment]
Agree with @izqui and @john-light here, it seems counterintuitive
